### ISSUE TITLE
Unable to add crate as dependency using git link

### ISSUE THREAD

**Issue by Brandon-Huu** [rydb/bevy_serialization_urdf#1]
Honestly have no idea, I've never had to go down a dependency rabbit hole before

# Steps to reproduce

1) cargo init
2) cargo add bevy_serialization_urdf --git https://github.com/rydb/bevy_serialization_urdf
3)
![image](https://github.com/rydb/bevy_serialization_urdf/assets/103440971/c08e321b-4f12-4513-a3a7-762c899a4fd9)

**Comment by rydb** [comment]
I'll check out putting the local testing version bevy_serialization_extras inside `[patch]`.

I think I published it so that it assumes you had bevy_serialization_extras in the folder net to it.. I'll fix that.

**Comment by rydb** [comment]
resolved
